### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by Daantaa** [PanKunik/buber-dinner#1]
I get this when I try to visit  https://localhost:7122 or  https://localhost:5258 :
 
This localhost page can’t be found
No webpage was found for the web address: https://localhost:7122/

HTTP ERROR 404

**Comment by PanKunik** [comment]
Hi!
First I want to clarify that this repository is following YoutTube's tutorial from `Amichai Mantinband`. This project is for learning puproses :)

Answering to your issue - this project doesn't have any UI for exploring resources. So you have to point to specified resource to get response. Now, application has two resources:

### Register
`[POST] /authentication/register` with example payload:
```json
{
    "firstName": "Tajma",
    "lastName": "Heinz",
    "email": "t.heinz@ex.com",
    "password": "Pwd12345."
}
```

Response:
```json
{
  "id": "f1308be5-9050-4992-be3d-419f26bb1654",
  "firstName": "Tajma",
  "lastName": "Heinz",
  "email": "t.heinz@ex.com",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJzdWIiOiJmMTMwOGJlNS05MDUwLTQ5OTItYmUzZC00MTlmMjZiYjE2NTQiLCJnaXZlbl9uYW1lIjoiVGFqbWEiLCJmYW1pbHlfbmFtZSI6IkhlaW56IiwianRpIjoiMjk1MDJhYmQtNDc4Mi00ZDgwLThiNmUtYjE1MThjNmQ0ZDFjIiwiZXhwIjoxNjU4ODU5NDI0LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.bBc8n94XDGQhHt64wXkazvLt8uiBIeBo5ltsGU3cT3A"
}
```

### Login 
`[POST] /authentication/login` with example payload:
```json
{
    "email": "t.heinz@contoso.com",
    "password": "Pwd12345."
}
```

Response:
```json
{
  "id": "b924e770-e89c-4e3c-8e57-7b4d8176f893",
  "firstName": "Tajma",
  "lastName": "Heinz",
  "email": "t.heinz@contoso.com",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJzdWIiOiJiOTI0ZTc3MC1lODljLTRlM2MtOGU1Ny03YjRkODE3NmY4OTMiLCJnaXZlbl9uYW1lIjoiVGFqbWEiLCJmYW1pbHlfbmFtZSI6IkhlaW56IiwianRpIjoiNjIwMDZmYTktZDc2My00ZTkxLWI3MTItOTNkOWQwYTU5NTI2IiwiZXhwIjoxNjU4ODU5NDczLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.ySWliskBsXivhnOM8nXfKehISjvxL4uFRWnVXcTn8M4"
}
```

Any other request would response in `NotFound 404`, because they aren't mapped to any URI.

If you have any questions, feel free to write them here :)
